### PR TITLE
Fix: multiple styling tokens in ANSI escape sequence

### LINKED ISSUE #97: Could you support standard ANSI intensity format?
According to https://en.wikipedia.org/wiki/ANSI_escape_code, one can add `;1` to display bright/bold text. But this currently doesn't work in bpython, instead, I have to prefix colored text with `\033[1m` to get bold effect.

screen shot 2017-03-14 at 11 33 11 pm

The inconsistency with standard ANSI escape code brings trouble to code that relies on it. Taking my current work [pdir2](https://github.com/laike9m/pdir2) as an example, [color](https://github.com/laike9m/pdir2/blob/master/pdir/constants.py#L189) can't be properly displayed in bpython.

I would like to know if you have plan to support this? I understand that it may conflicts with the current design/API, and it's totally ok if you don't.

### PR DESCRIPTION
**Pull request by ata2001**
Fixes #97.

### CODE REVIEW

**Comment by thomasballinger** [comment]
Could you add a test to TestFmtStrParsing to show how you changed the behavior here?

**Comment by thomasballinger** [comment]
Great, thanks!

**Comment by ata2001** [comment]
>Could you add a test to TestFmtStrParsing to show how you changed the behavior here?

Sure.

**Comment by laike9m** [comment]
Thanks @ata2001 . 

When will this change be applied to bpython, next version?

**Pull request merged**
